/**
 * Adaptive Assessment & IRT Quiz Engine
 * Part of the Adaptive Learning Intelligence System
 */

(function(window) {
    "use strict";

    // Standard Bank of Adaptive Questions (aligned with OS curriculum)
    const ADAPTIVE_QUESTION_BANK = [
        {
            id: "q_sched_1",
            conceptId: "c_cpu_sched",
            difficulty: "easy",
            question: "In CPU scheduling, which algorithm can suffer from the 'Convoy Effect' where short processes wait behind a long CPU-burst process?",
            options: [
                "A. First-Come, First-Served (FCFS)",
                "B. Round Robin (RR) with small quantum",
                "C. Shortest Job First (SJF) Preemptive",
                "D. Multilevel Queue Scheduling"
            ],
            answer: "A",
            explanation: "FCFS is non-preemptive. If a CPU-bound process with a huge burst arrives first, all following short I/O-bound processes are stuck behind it, causing the Convoy Effect and severely degrading average turnaround time."
        },
        {
            id: "q_sched_2",
            conceptId: "c_cpu_sched",
            difficulty: "medium",
            question: "Consider 3 processes arriving at time 0 with burst times P1=24ms, P2=3ms, P3=3ms. Under FCFS, what is the average waiting time?",
            options: [
                "A. 17 ms",
                "B. 27 ms",
                "C. 3 ms",
                "D. 30 ms"
            ],
            answer: "A",
            explanation: "Waiting times: P1 waits 0ms, P2 waits 24ms, P3 waits 24 + 3 = 27ms. Average waiting time = (0 + 24 + 27) / 3 = 51 / 3 = 17 ms."
        },
        {
            id: "q_sync_1",
            conceptId: "c_sync_mutex",
            difficulty: "medium",
            question: "What is the primary difference between a binary semaphore and a mutex?",
            options: [
                "A. A mutex has an ownership concept (only the locking thread can unlock it), while a semaphore does not",
                "B. Binary semaphores can hold any integer value, while mutexes hold only 0 or 1",
                "C. Mutexes cannot be used for critical sections",
                "D. Binary semaphores are implemented in hardware while mutexes are only software"
            ],
            answer: "A",
            explanation: "Mutex implies ownership: only the process or thread that locked the mutex is allowed to unlock it. In contrast, a binary semaphore can be signaled (unlocked) by any thread, making it ideal for signaling and event notification."
        },
        {
            id: "q_deadlock_1",
            conceptId: "c_deadlock",
            difficulty: "hard",
            question: "In Banker's Algorithm for deadlock avoidance, a system with 12 total units of Resource R has: P0 holds 5 (Max 10), P1 holds 2 (Max 4), P2 holds 2 (Max 9). Available R = 3. Is the system in a safe state?",
            options: [
                "A. Yes, with safe sequence <P1, P0, P2>",
                "B. No, the system is deadlocked",
                "C. No, the system is in an unsafe state",
                "D. Yes, with safe sequence <P0, P1, P2>"
            ],
            answer: "A",
            explanation: "Need matrix: P0 needs 5, P1 needs 2, P2 needs 7. Available = 3. P1's need (2) <= Available (3), so allocate to P1. When P1 completes, Available becomes 3 + 2 = 5. Now P0's need (5) <= 5. P0 completes and releases 5, Available becomes 10. Finally P2 (needs 7) can run. Safe sequence: <P1, P0, P2>."
        },
        {
            id: "q_mem_1",
            conceptId: "c_mem_paging",
            difficulty: "easy",
            question: "What hardware component is responsible for translating a logical/virtual memory address into a physical RAM address?",
            options: [
                "A. Memory Management Unit (MMU)",
                "B. Arithmetic Logic Unit (ALU)",
                "C. Direct Memory Access Controller (DMA)",
                "D. Program Counter (PC)"
            ],
            answer: "A",
            explanation: "The Memory Management Unit (MMU) is the hardware device that maps logical addresses generated by the CPU to physical addresses in physical memory."
        },
        {
            id: "q_mem_2",
            conceptId: "c_virt_mem",
            difficulty: "medium",
            question: "Under which page replacement algorithm does 'Belady's Anomaly' (more page frames causing more page faults) occur?",
            options: [
                "A. FIFO (First-In, First-Out)",
                "B. LRU (Least Recently Used)",
                "C. Optimal (OPT)",
                "D. LFU (Least Frequently Used)"
            ],
            answer: "A",
            explanation: "Belady's Anomaly occurs in FIFO page replacement because FIFO is not a stack algorithm. Algorithms like LRU and Optimal satisfy the inclusion property and never suffer from Belady's Anomaly."
        },
        {
            id: "q_file_1",
            conceptId: "c_file_sys",
            difficulty: "medium",
            question: "Which file allocation method supports efficient random direct access to any block without suffering from external fragmentation?",
            options: [
                "A. Indexed Allocation",
                "B. Contiguous Allocation",
                "C. Linked Allocation without FAT",
                "D. Pure Sequential Allocation"
            ],
            answer: "A",
            explanation: "Indexed allocation brings all disk block pointers together into an index block. This provides direct random access without external fragmentation (unlike contiguous allocation), and avoids sequential traversal (unlike linked allocation)."
        },
        {
            id: "q_disk_1",
            conceptId: "c_disk_sched",
            difficulty: "medium",
            question: "In disk scheduling, what is the primary advantage of C-SCAN (Circular SCAN) over standard SCAN?",
            options: [
                "A. Provides more uniform waiting times for requests at the inner/outer edges",
                "B. Completely eliminates disk seek latency",
                "C. Services requests in purely random order",
                "D. Moves head in only one direction forever without reversing"
            ],
            answer: "A",
            explanation: "In standard SCAN, requests near the edges are serviced twice in rapid succession (on the way to the end and back), while requests in the middle wait longer. C-SCAN treats cylinders as a circular list, providing a much more uniform waiting distribution."
        }
    ];

    class AdaptiveQuizEngine {
        constructor(containerIds = {}) {
            this.containerIds = containerIds;
            this.questions = [];
            this.currentIndex = 0;
            this.selectedOption = null;
            this.timerSeconds = 900;
            this.timerInterval = null;
            this.questionStartTime = Date.now();
            this.examId = null;
            this.onAttemptRecorded = null;
            this.onQuizCompleted = null;
            this.resultsSubmitted = false;
        }

        init(examId, questionsFromBackend = [], { allowDemoQuestions = false, failureMessage = "No validated mock is available." } = {}) {
            this.examId = examId;
            clearInterval(this.timerInterval);
            this.timerSeconds = 900;
            this.currentIndex = 0;
            this.selectedOption = null;
            this.resultsSubmitted = false;

            if (questionsFromBackend && questionsFromBackend.length > 0) {
                this.questions = questionsFromBackend.map((q, idx) => ({
                    id: q._id || `q_${idx}`,
                    conceptId: q.conceptId || this.guessConcept(q.question),
                    difficulty: q.difficulty || "medium",
                    question: q.question,
                    options: q.options,
                    answer: q.answer,
                    explanation: q.explanation || "Detailed conceptual breakdown based on the course syllabus."
                }));
            } else if (allowDemoQuestions) {
                this.questions = JSON.parse(JSON.stringify(ADAPTIVE_QUESTION_BANK));
            } else {
                this.questions = [];
                this.renderUnavailable(failureMessage);
                return;
            }

            this.startTimer();
            this.renderQuestion();
        }

        renderUnavailable(message) {
            const qNumEl = document.getElementById("mock-question-num");
            const progressFill = document.getElementById("mock-progress-fill");
            const qTextEl = document.getElementById("question-container");
            const optsEl = document.getElementById("mock-options");
            const expEl = document.getElementById("explanation");
            const checkBtn = document.getElementById("check-answer-btn");
            const prevBtn = document.getElementById("prev-btn");
            const nextBtn = document.getElementById("next-btn");

            if (qNumEl) qNumEl.innerText = "Mock unavailable";
            if (progressFill) progressFill.style.width = "0%";
            if (qTextEl) qTextEl.innerHTML = `<div class="empty-state"><p>${String(message || "No validated mock is available.")}</p></div>`;
            if (optsEl) optsEl.innerHTML = "";
            if (expEl) expEl.style.display = "none";
            [checkBtn, prevBtn, nextBtn].forEach(button => {
                if (button) button.disabled = true;
            });
        }

        guessConcept(text) {
            const lower = (text || "").toLowerCase();
            if (lower.includes("schedul") || lower.includes("fcfs") || lower.includes("round robin")) return "c_cpu_sched";
            if (lower.includes("deadlock") || lower.includes("banker")) return "c_deadlock";
            if (lower.includes("page") || lower.includes("belady") || lower.includes("virtual memory")) return "c_virt_mem";
            if (lower.includes("mmu") || lower.includes("address")) return "c_mem_paging";
            if (lower.includes("semaphore") || lower.includes("mutex") || lower.includes("critical section")) return "c_sync_mutex";
            if (lower.includes("disk") || lower.includes("scan") || lower.includes("c-look")) return "c_disk_sched";
            if (lower.includes("file") || lower.includes("directory") || lower.includes("allocation")) return "c_file_sys";
            return "c_proc_mgmt";
        }

        startTimer() {
            clearInterval(this.timerInterval);
            this.updateTimerDisplay();
            this.timerInterval = setInterval(() => {
                this.timerSeconds--;
                this.updateTimerDisplay();
                if (this.timerSeconds <= 0) {
                    clearInterval(this.timerInterval);
                    this.showResults();
                }
            }, 1000);
        }

        updateTimerDisplay() {
            const timerEl = document.getElementById("mock-timer");
            if (!timerEl) return;
            const m = Math.floor(this.timerSeconds / 60);
            const s = this.timerSeconds % 60;
            timerEl.innerText = `${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")}`;
        }

        renderQuestion() {
            const q = this.questions[this.currentIndex];
            if (!q) return;

            this.questionStartTime = Date.now();
            this.selectedOption = q.chosen || null;

            // UI Elements
            const qNumEl = document.getElementById("mock-question-num");
            const progressFill = document.getElementById("mock-progress-fill");
            const qTextEl = document.getElementById("question-container");
            const optsEl = document.getElementById("mock-options");
            const expEl = document.getElementById("explanation");
            const expTextEl = document.getElementById("explanation-text");
            const checkBtn = document.getElementById("check-answer-btn");
            const prevBtn = document.getElementById("prev-btn");
            const nextBtn = document.getElementById("next-btn");

            if (qNumEl) qNumEl.innerText = `Question ${this.currentIndex + 1} of ${this.questions.length}`;
            if (progressFill) progressFill.style.width = `${((this.currentIndex + 1) / this.questions.length) * 100}%`;

            // Question text + difficulty badge
            if (qTextEl) {
                const diffBadgeClass = q.difficulty === "easy" ? "badge-easy" : q.difficulty === "hard" ? "badge-hard" : "badge-medium";
                qTextEl.innerHTML = `
                    <div style="display:flex;align-items:center;gap:8px;margin-bottom:12px;">
                        <span class="quiz-diff-badge ${diffBadgeClass}">${q.difficulty.toUpperCase()}</span>
                        <span style="font-size:0.75rem;color:var(--text-muted);">Adaptive IRT Item</span>
                    </div>
                    <div>${q.question}</div>
                `;
            }

            if (optsEl) {
                optsEl.innerHTML = "";
                const isChecked = q.checked === true;

                q.options.forEach(optText => {
                    const letter = optText.trim()[0];
                    const card = document.createElement("div");
                    card.className = "mock-option-card";

                    if (isChecked) {
                        if (letter === q.answer) card.classList.add("correct");
                        else if (letter === q.chosen) card.classList.add("incorrect");
                    } else if (letter === this.selectedOption) {
                        card.classList.add("selected");
                    }

                    card.innerHTML = `
                        <div class="mock-option-badge">${letter}</div>
                        <div class="mock-option-text">${optText}</div>
                    `;

                    if (!isChecked) {
                        card.addEventListener("click", () => {
                            optsEl.querySelectorAll(".mock-option-card").forEach(c => c.classList.remove("selected"));
                            card.classList.add("selected");
                            this.selectedOption = letter;
                            q.chosen = letter;
                            if (checkBtn) checkBtn.disabled = false;
                        });
                    }
                    optsEl.appendChild(card);
                });
            }

            if (expEl && expTextEl) {
                if (q.checked) {
                    expTextEl.innerHTML = `
                        <div style="margin-bottom:8px;">${q.explanation}</div>
                        <div style="font-size:0.78rem;color:var(--text-muted);border-top:1px solid var(--border-color);padding-top:6px;margin-top:6px;">
                            ${q.isCorrect
                                ? "<span style='color:var(--color-success);font-weight:600;'>+ Cognitive Mastery Increased</span> · High probability of concept retention."
                                : "<span style='color:var(--color-danger);font-weight:600;'>! Knowledge Gap Detected</span> · Recommended to review prerequisite in Knowledge Graph."}
                        </div>
                    `;
                    expEl.style.display = "block";
                    if (checkBtn) checkBtn.disabled = true;
                } else {
                    expEl.style.display = "none";
                    if (checkBtn) checkBtn.disabled = !this.selectedOption;
                }
            }

            if (prevBtn) prevBtn.disabled = this.currentIndex === 0;
            if (nextBtn) {
                const isLast = this.currentIndex === this.questions.length - 1;
                nextBtn.innerText = isLast ? "Finish & Submit" : "Next";
                nextBtn.disabled = false;
            }
        }

        checkCurrentAnswer() {
            const q = this.questions[this.currentIndex];
            if (!q || !this.selectedOption || q.checked) return;

            const timeTakenSec = Math.round((Date.now() - this.questionStartTime) / 1000);
            q.checked = true;
            q.isCorrect = this.selectedOption === q.answer;

            // Feed to Cognitive Model
            if (window.cognitiveModel) {
                const result = window.cognitiveModel.recordAttempt({
                    conceptId: q.conceptId,
                    isCorrect: q.isCorrect,
                    timeTakenSec,
                    difficulty: q.difficulty,
                    questionText: q.question
                });

                if (this.onAttemptRecorded) {
                    this.onAttemptRecorded(result);
                }
            }

            this.renderQuestion();
        }

        nextQuestion() {
            if (this.currentIndex < this.questions.length - 1) {
                this.currentIndex++;
                this.renderQuestion();
            } else {
                this.showResults();
            }
        }

        prevQuestion() {
            if (this.currentIndex > 0) {
                this.currentIndex--;
                this.renderQuestion();
            }
        }

        showResults() {
            clearInterval(this.timerInterval);
            const quizCard = document.getElementById("mock-quiz-card");
            const resultCard = document.getElementById("mock-result-card");
            if (quizCard) quizCard.style.display = "none";
            if (resultCard) resultCard.style.display = "block";

            const score = this.questions.filter(q => q.isCorrect).length;
            const total = this.questions.length;
            const scoreEl = document.getElementById("score-display-value");
            const evalEl = document.getElementById("score-evaluation");
            const subEl = document.getElementById("score-subtext");

            if (scoreEl) scoreEl.innerText = `${score}/${total}`;

            if (!this.resultsSubmitted && this.onQuizCompleted) {
                this.resultsSubmitted = true;
                Promise.resolve(this.onQuizCompleted({ examId: this.examId, score, total })).catch(() => {});
            }

            const pct = (score / total) * 100;
            if (pct >= 80) {
                if (evalEl) { evalEl.innerText = "Mastery Demonstrated!"; evalEl.style.color = "var(--color-success)"; }
                if (subEl) subEl.innerText = "Outstanding accuracy. Your DKT concept mastery scores have been updated favorably.";
            } else if (pct >= 50) {
                if (evalEl) { evalEl.innerText = "Moderate Conceptual Grasp"; evalEl.style.color = "var(--color-primary-light)"; }
                if (subEl) subEl.innerText = "Solid effort. Review the flagged weak concepts in your Knowledge Graph to solidify memory.";
            } else {
                if (evalEl) { evalEl.innerText = "Significant Conceptual Blindspots"; evalEl.style.color = "var(--color-danger)"; }
                if (subEl) subEl.innerText = "Prerequisite gaps detected. Use the Doubt Solver and step-by-step roadmap to review foundational topics.";
            }
        }

        restart() {
            this.questions.forEach(q => {
                q.chosen = null;
                q.checked = false;
                q.isCorrect = false;
            });
            const quizCard = document.getElementById("mock-quiz-card");
            const resultCard = document.getElementById("mock-result-card");
            if (quizCard) quizCard.style.display = "flex";
            if (resultCard) resultCard.style.display = "none";

            this.currentIndex = 0;
            this.timerSeconds = 900;
            this.resultsSubmitted = false;
            this.startTimer();
            this.renderQuestion();
        }
    }

    window.AdaptiveQuizEngine = AdaptiveQuizEngine;

})(window);
